import './globals.css'
import type { Metadata } from 'next'
import { Barlow_Semi_Condensed } from 'next/font/google'

const barlow = Barlow_Semi_Condensed({weight:['500','600'],subsets: ['latin'], })

export const metadata: Metadata = {
  title: 'Grid-tempalte',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` lg:py-24 py-12 px-6 max-w-7xl mx-auto bg-[#ecf2f8] ${barlow.className}`}>{children}</body>
    </html>
  )
}
